# 01 - Data Cleaning & Preprocessing
**Retail Sales Analysis Project**

In [1]:
import pandas as pd
import os

# Force correct working directory
os.chdir('..')   # This moves up one level to the project root

print("Current working directory:", os.getcwd())
print("\nFiles in data/raw/:")
print(os.listdir('data/raw'))

# Load the dataset
df = pd.read_csv('data/raw/retail_sales_dataset.csv')

print("\n✅ SUCCESS! File loaded successfully!")
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())
df.head()

Current working directory: C:\Users\IEK ICT\retail-sales-analysis

Files in data/raw/:
['.ipynb_checkpoints', 'retail_sales_dataset.csv']

✅ SUCCESS! File loaded successfully!
Shape: (1000, 9)
Columns: ['Transaction ID', 'Date', 'Customer ID', 'Gender', 'Age', 'Product Category', 'Quantity', 'Price per Unit', 'Total Amount']

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100

In [2]:
# Check for missing values
print("Missing values:\n", df.isnull().sum())

# Check for duplicates
print("\nDuplicate rows:", df.duplicated().sum())

Missing values:
 Transaction ID      0
Date                0
Customer ID         0
Gender              0
Age                 0
Product Category    0
Quantity            0
Price per Unit      0
Total Amount        0
dtype: int64

Duplicate rows: 0

In [4]:
# Run the preprocessing script using absolute path from project root
import os
import sys

# Move to project root (in case we are inside notebooks folder)
if os.getcwd().endswith('notebooks'):
    os.chdir('..')

print("Current working directory:", os.getcwd())

# Run the preprocessing script
%run scripts/data_preprocessing.py

Current working directory: C:\Users\IEK ICT\retail-sales-analysis
Dataset shape: (1000, 13)
Date range: 2023-01-01 00:00:00 to 2024-01-01 00:00:00
✅ Data cleaned and saved to data/processed/cleaned_sales.csv
   Transaction ID       Date Customer ID  Gender  Age Product Category  \
0               1 2023-11-24     CUST001    Male   34           Beauty
1               2 2023-02-27     CUST002  Female   26         Clothing
2               3 2023-01-13     CUST003    Male   50      Electronics
3               4 2023-05-21     CUST004    Male   37         Clothing
4               5 2023-05-06     CUST005    Male   30           Beauty

   Quantity  Price per Unit  Total Amount  Month Day_of_Week  Revenue  \
0         3              50           150     11      Friday      150
1         2             500          1000      2      Monday     1000
2         1              30            30      1      Friday       30
3         1             500           500      5      Sunday      500
4         2              50           100      5    Saturday      100

  Age_Group
0     26-35
1     26-35
2     36-50
3     36-50
4     26-35

In [5]:
# Load and check the cleaned data
import pandas as pd

df_clean = pd.read_csv('data/processed/cleaned_sales.csv')
print("Cleaned dataset shape:", df_clean.shape)
print("\nFirst 5 rows:")
df_clean.head()

Cleaned dataset shape: (1000, 13)

First 5 rows:

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount,Month,Day_of_Week,Revenue,Age_Group
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150,11,Friday,150,26-35
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000,2,Monday,1000,26-35
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30,1,Friday,30,36-50
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500,5,Sunday,500,36-50
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100,5,Saturday,100,26-35